const genusData = [
    "Iron Armor Pokémon",
    "Symbol Pokémon",
    "Rock Peak Pokémon",
    "Legendary Pokémon",
    "Pitch-Black Pokémon",
    "Chimp Pokémon",
    "Tadpole Pokémon",
    "Jolly Pokémon",
    "Big-Hearted Pokémon",
    "Bronze Bell Pokémon",
    "Long Nose Pokémon",
    "Judo Pokémon",
    "Darkness Pokémon",
    "Dragon Pokémon",
    "Duck Pokémon",
    "Float Whale Pokémon",
    "Tiger Cat Pokémon",
    "Stag Beetle Pokémon",
    "Vine Pokémon",
    "Spatial Pokémon",
    "Temporal Pokémon",
    "Diving Pokémon",
    "Lazy Pokémon",
    "Cheering Pokémon",
    "Land Snake Pokémon",
    "Handstand Pokémon",
    "Cruel Pokémon",
    "Endurance Pokémon",
    "Mega Fire Pig Pokémon",
    "Fang Scorpion Pokémon",
    "Sky High Pokémon",
    "Scratch Cat Pokémon",
    "Weather Pokémon",
    "Shellfish Pokémon",
    "Vibration Pokémon",
    "Seafaring Pokémon",
    "Thunderbolt Pokémon",
    "Formidable Pokémon",
    "Hippo Pokémon",
    "Live Coal Pokémon",
    "Transport Pokémon",
    "Fang Snake Pokémon",
    "Puppy Pokémon",
    "Clap Pokémon",
    "Gripper Pokémon",
    "Predator Pokémon",
    "Acorn Pokémon",
    "Cactus Pokémon",
    "Bronze Pokémon",
    "Discharge Pokémon",
    "Slacker Pokémon",
    "Mouse Pokémon",
    "Hearing Pokémon",
    "Eruption Pokémon",
    "Polka Dot Pokémon",
    "Freeze Pokémon",
    "Swine Pokémon",
    "Frog Pokémon",
    "Cave Pokémon",
    "Tiny Bee Pokémon",
    "Rock Skin Pokémon",
    "Armor Bird Pokémon",
    "Patient Pokémon",
    "Grove Pokémon",
    "Hard Shell Pokémon",
    "Ice Break Pokémon",
    "Moth Pokémon",
    "Rainbow Pokémon",
    "Humming Pokémon",
    "Rock Snake Pokémon",
    "Sea Drifter Pokémon",
    "Fresh Snow Pokémon",
    "Blaze Pokémon",
    "Gratitude Pokémon",
    "Frost Tree Pokémon",
    "Magical Pokémon",
    "Tender Pokémon",
    "Weed Pokémon",
    "Punching Pokémon",
    "Aura Pokémon",
    "Rendezvous Pokémon",
    "Shield Pokémon",
    "Meditate Pokémon",
    "Proud Pokémon",
    "Flash Pokémon",
    "Snake Pokémon",
    "Bug Catcher Pokémon",
    "Pig Pokémon",
    "Rushing Pokémon",
    "Beak Pokémon",
    "Ember Pokémon",
    "Bubble Jet Pokémon",
    "Wild Pigeon Pokémon",
    "Brutal Pokémon",
    "Thorn Pokémon",
    "Courting Pokémon",
    "Delivery Pokémon",
    "Beehive Pokémon",
    "Disaster Pokémon",
    "Longevity Pokémon",
    "Ninja Pokémon",
    "Twin Bird Pokémon",
    "Cocoon Pokémon",
    "Spikes Pokémon",
    "Little Bear Pokémon",
    "Blade Pokémon",
    "Beaver Pokémon",
    "Compass Pokémon",
    "Sun Pokémon",
    "Toxic Mouth Pokémon",
    "Savage Pokémon",
    "Kitten Pokémon",
    "Aqua Rabbit Pokémon",
    "Cotton Bird Pokémon",
    "Electrified Pokémon",
    "Clay Doll Pokémon",
    "Time Travel Pokémon",
    "Blossom Pokémon",
    "Star Shape Pokémon",
    "Forest Pokémon",
    "Lightning Pokémon",
    "Spitfire Pokémon",
    "Knowledge Pokémon",
    "Hermit Crab Pokémon",
    "Megaton Pokémon",
    "Water Fish Pokémon",
    "Fire Mouse Pokémon",
    "Bat Pokémon",
    "Bagworm Pokémon",
    "Long Body Pokémon",
    "Music Note Pokémon",
    "EleSquirrel Pokémon",
    "Grass Monkey Pokémon",
    "Coal Pokémon",
    "Eyeball Pokémon",
    "Poison Bee Pokémon",
    "Bright Pokémon",
    "Scarecrow Pokémon",
    "Compressed Pokémon",
    "Sea Lion Pokémon",
    "Wool Pokémon",
    "Cotton Puff Pokémon",
    "Ball Roll Pokémon",
    "Dream Eater Pokémon",
    "Parent Pokémon",
    "Lava Dome Pokémon",
    "Manipulate Pokémon",
    "Lava Pokémon",
    "Jellyfish Pokémon",
    "Lizard Pokémon",
    "Wild Monkey Pokémon",
    "Drill Pokémon",
    "Poison Pin Pokémon",
    "Playful Pokémon",
    "Big Voice Pokémon",
    "Gas Pokémon",
    "Classy Cat Pokémon",
    "Milk Cow Pokémon",
    "Nurturing Pokémon",
    "Barnacle Pokémon",
    "Hibernator Pokémon",
    "Mushroom Pokémon",
    "Butterfly Pokémon",
    "Plasma Pokémon",
    "Prim Pokémon",
    "New Species Pokémon",
    "Wood Gecko Pokémon",
    "Angler Pokémon",
    "Flowering Pokémon",
    "Iron Ball Pokémon",
    "Spark Pokémon",
    "Sewing Pokémon",
    "Colossal Pokémon",
    "Rabbit Pokémon",
    "Imitation Pokémon",
    "Big Eater Pokémon",
    "Aqua Mouse Pokémon",
    "Requiem Pokémon",
    "Worm Pokémon",
    "Sea Weasel Pokémon",
    "Cricket Pokémon",
    "Mystic Pokémon",
    "Ant Pit Pokémon",
    "Plate Pokémon",
    "Bite Pokémon",
    "Pond Skater Pokémon",
    "Big Boss Pokémon",
    "Drowsing Pokémon",
    "Happiness Pokémon",
    "Iron Pokémon",
    "Atrocious Pokémon",
    "Dark Pokémon",
    "Mysterious Pokémon",
    "Scout Pokémon",
    "Scorpion Pokémon",
    "Subterrene Pokémon",
    "Discipline Pokémon",
    "Rock Head Pokémon",
    "Volcano Pokémon",
    "Young Fowl Pokémon",
    "Cottonweed Pokémon",
    "Iron Leg Pokémon",
    "Mold Pokémon",
    "Eon Pokémon",
    "Fish Pokémon",
    "Starling Pokémon",
    "Wily Pokémon",
    "Five Star Pokémon",
    "Mantle Pokémon",
    "Curlipede Pokémon",
    "Bounce Pokémon",
    "Emotion Pokémon",
    "Poison Gas Pokémon",
    "Herb Pokémon",
    "Grass Snake Pokémon",
    "Emanation Pokémon",
    "Iron Snake Pokémon",
    "Mantis Pokémon",
    "Dopey Pokémon",
    "High Temp Pokémon",
    "Catty Pokémon",
    "Mud Fish Pokémon",
    "Goldfish Pokémon",
    "Superpower Pokémon",
    "Wild Duck Pokémon",
    "Seagull Pokémon",
    "Poison Moth Pokémon",
    "Aurora Pokémon",
    "Hypnosis Pokémon",
    "Penguin Pokémon",
    "Single Horn Pokémon",
    "Coconut Pokémon",
    "Continent Pokémon",
    "Thunder Pokémon",
    "Coral Pokémon",
    "Lookout Pokémon",
    "Long Tail Pokémon",
    "Snow Land Pokémon",
    "Ball Pokémon",
    "Leaf Pokémon",
    "Lunar Pokémon",
    "Embrace Pokémon",
    "Big Horn Pokémon",
    "Egg Pokémon",
    "Iceberg Pokémon",
    "Victory Pokémon",
    "Bud Pokémon",
    "Sea Basin Pokémon",
    "Ogre Scorpion Pokémon",
    "Evolution Pokémon",
    "Clear Wing Pokémon",
    "Whiskers Pokémon",
    "Cobra Pokémon",
    "Gleam Eyes Pokémon",
    "Psi Pokémon",
    "Tiny Pigeon Pokémon",
    "Long Neck Pokémon",
    "Guts Pokémon",
    "Head Butt Pokémon",
    "Cherry Pokémon",
    "Wicked Pokémon",
    "Devious Pokémon",
    "Sharp Claw Pokémon",
    "Kiss Pokémon",
    "Kite Pokémon",
    "Spot Panda Pokémon",
    "Bivalve Pokémon",
    "Mach Pokémon",
    "Carefree Pokémon",
    "Bird Pokémon",
    "Thorn Monkey Pokémon",
    "Land Shark Pokémon",
    "Blimp Pokémon",
    "Kicking Pokémon",
    "Tiny Leaf Pokémon",
    "Hairy Bug Pokémon",
    "Chick Pokémon",
    "Megapede Pokémon",
    "Fairy Pokémon",
    "Shadow Pokémon",
    "Plump Mouse Pokémon",
    "Rogue Pokémon",
    "Deceiver Pokémon",
    "Licking Pokémon",
    "Numb Pokémon",
    "Barrier Pokémon",
    "Poison Bag Pokémon",
    "Bulb Pokémon",
    "Puppet Pokémon",
    "Beckon Pokémon",
    "Swallow Pokémon",
    "Turtle Pokémon",
    "Fruit Pokémon",
    "DNA Pokémon",
    "Face Pokémon",
    "Verdant Pokémon",
    "Cat Ferret Pokémon",
    "Magnet Area Pokémon",
    "Intimidation Pokémon",
    "Genetic Pokémon",
    "Spray Pokémon",
    "Balloon Pokémon",
    "Loud Noise Pokémon",
    "Heavyweight Pokémon",
    "Mole Pokémon",
    "Tiny Bird Pokémon",
    "River Crab Pokémon",
    "Meteorite Pokémon",
    "Wild Bull Pokémon",
    "Blast Pokémon",
    "Twin Tusk Pokémon",
    "Human Shape Pokémon",
    "South Sea Pokémon",
    "Sleeping Pokémon",
    "Mime Pokémon",
    "Centipede Pokémon",
    "Triple Bird Pokémon",
    "Screech Pokémon",
    "Bone Keeper Pokémon",
    "Flower Pokémon",
    "Stomach Pokémon",
    "Electric Pokémon",
    "Long Leg Pokémon",
    "Leaf-Wrapped Pokémon",
    "Fly Scorpion Pokémon",
    "Shed Pokémon",
    "Lonely Pokémon",
    "Desert Croc Pokémon",
    "Wish Pokémon",
    "Ball Whale Pokémon",
    "Neon Pokémon",
    "Tiny Turtle Pokémon",
    "Skunk Pokémon",
    "Light Pokémon",
    "Sea Slug Pokémon",
    "Sea Otter Pokémon",
    "Old Shrimp Pokémon",
    "Loyal Dog Pokémon",
    "Karate Pokémon",
    "Feeling Pokémon",
    "Ruffian Pokémon",
    "Virtual Pokémon",
    "Magnet Pokémon",
    "Deep Sea Pokémon",
    "Snow Hat Pokémon",
    "Jet Pokémon",
    "Hostile Pokémon",
    "Playhouse Pokémon",
    "Fossil Pokémon",
    "Wing Fish Pokémon",
    "Water Weed Pokémon",
    "Fox Pokémon",
    "Willpower Pokémon",
    "String Spit Pokémon",
    "Bell Pokémon",
    "Royal Pokémon",
    "Regal Pokémon",
    "Alpha Pokémon",
    "Color Swap Pokémon",
    "Transform Pokémon",
    "Tiny Swallow Pokémon",
    "Fire Horse Pokémon",
    "Windveiled Pokémon",
    "Sludge Pokémon",
    "Muscular Pokémon",
    "Sea Lily Pokémon",
    "Tiny Mouse Pokémon",
    "Big Jaw Pokémon",
    "Water Bird Pokémon",
    "Geyser Pokémon",
    "Marionette Pokémon",
    "Painter Pokémon",
    "Tiny Raccoon Pokémon",
    "Jubilee Pokémon",
    "Firefly Pokémon",
    "Moonlight Pokémon",
    "Insect Pokémon",
    "Spiral Pokémon",
    "Seed Pokémon",
    "Whisper Pokémon",
    "Trainee Pokémon",
    "Forbidden Pokémon",
    "Ogre Darner Pokémon",
    "Bonsai Pokémon",
    "Arm Thrust Pokémon",
    "Flycatcher Pokémon",
    "Ore Pokémon",
    "Renegade Pokémon",
    "Fire Pig Pokémon",
    "Armor Pokémon",
    "Scuffle Pokémon",
    "Wind Chime Pokémon",
    "Spike Ball Pokémon",
    "Emperor Pokémon",
    "Owl Pokémon",
    "Bouquet Pokémon",
    "Flame Pokémon",
    "Iron Claw Pokémon",
    "Pig Monkey Pokémon",
    "Pincer Pokémon",
    "Rock Pokémon",
  ];
  export default genusData;
  